name: Camouf 2
authors: [Ghosty, Solme]
version: ${version}
api-version: 1.21
description: Reproduction du KamoofSMP Saison 2
website: https://modrinth.com/plugin/camouf2
depend: [NickAPI]
main: me.ghosty.kamoof.KamoofSMP
commands:
  kamoofsmp:
    description: Commande globale
    aliases: [kamoof, camouf, camoufsmp]
  givehead:
    description: Se donne une tête
    permission: kamoofsmp.admin
  undisguise:
    description: Retire son déguisement
permissions:
  kamoofsmp.admin:
    description: Administrateur du serveur
