name: KamoofSMP
authors: [Ghosty, Solme]
version: ${version}
api-version: 1.21
description: Le KamoofSMP Saison 2 de Sohran
website: https://modrinth.com/plugin/kamoofsmp2
depend: [NickAPI]
main: me.ghosty.kamoof.KamoofSMP
commands:
  kamoofsmp:
    description: La commande principale du KamoofSMP
    aliases: [kamoof]
  givehead:
    description: Se donner n'importe quelle tête
    permission: kamoofsmp.admin
  undisguise:
    description: Retirer son déguisement
permissions:
  kamoofsmp.admin:
    description: Admin du KamoofSMP