name: KamoofSMP
authors: [ Ghosty, Solme ]
version: ${version}
api-version: 1.21
description: Reproduction du KamoofSMP Saison 2 de Sohran
website: https://modrinth.com/plugin/camouf2
depend: [ NickAPI ]
main: cc.ghosty.kamoof.KamoofSMP
commands:
  kamoofsmp:
    description: Commande globale du KamoofSMP
    aliases: [ kamoof, camouf, camoufsmp ]
  givehead:
    description: Se donner n'importe quelle tête
    permission: kamoofsmp.admin
  undisguise:
    description: Retirer son déguisement
permissions:
  kamoofsmp.admin:
    description: Administrateur du serveur